//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 04:39:08 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:SAML:2.0:metadata",
        xmlns = {
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "urn:oasis:names:tc:SAML:2.0:assertion", prefix = "saml"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "urn:oasis:names:tc:SAML:2.0:metadata", prefix = "md"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix = "ds"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2001/04/xmlenc#", prefix = "xenc"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "urn:oasis:names:tc:SAML:metadata:ui", prefix = "mdui"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "urn:oasis:names:tc:SAML:metadata:attribute", prefix = "mdattr"),
                @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://id.swedenconnect.se/authn/1.0/principal-selection/ns", prefix = "psc")},
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.signatureservice.messages.saml2.metadata.jaxb;
