= Signservice-messages Project

This project is a fork of the Certservice-messages Project. The Signature service project will henceforth
depend on this project instead.

== Remarks

** This project will be made available publicly, as a dependency of signservice-support-lib
** Target namespaces for the xml schemas remain unchanged for now
** Parts of the codebase not required for Signature service will be removed, as they are discovered
** All the sections below are documentation inherited from the Certservice-messages Project

== Certservice-messages Project

This project containing Java code to generate and parse various messages within other certservice projects.

It mainly consists of the following parts:


CS Message 2.0 (core message format) with a set of Payload Parsers (which also are generators).

** Credential Management Payload Parser
** Key Store Management Payload Parser
** System Configuration Payload Parser
** Assertion Payload Parser
** Authorization Payload Parser
** Encrypted CS Message Payload Parser

PKI Message generator (Older core message format) containing messages for credential management.

== Updated Dependencies

In order to mitigate security vulnerabilties in XMLSEC 1.5.7 it has been upgraded to 2.2.3 which
updated a few dependencies to the build of this library:

 * slf4j-api-1.7.30.jar
 * xmlsec-2.2.3.jar

Other dependencies are:

 * bcprov-jdk15on-1.47.jar

== Message Specification Documentation

For detailed documentation of each available message and its content see directory src/site/resources.

== Using CS Message 2.0 Framework to generate or parse messages.

Before you start generating or parsing a CS Message 2.0 you need to initialize it once using a call to se.signatureservice.message.csmessages.initCSMessageParser(MessageSecurityProvider securityProvider, Properties config). You can later retrieve the CSMessageParser using the getCSMessageParser() metod. As security provider you can either implement your own of use the se.signatureservice.message.SimpleMessageSecurityProvider.

== Main Configuration Settings

By default is the DefaultCSMessageManager returned, but a custom implementation implementing CSMessageParser can be used as well

Settings for the configuration manager are:

|===
|Key |Description |Default value 

|csmessage.parser.impl |Implementation of CS Message Parser that should be used. |se.signatureservice.message.csmessages.DefaultCSMessageParser
|===

== DefaultCSMessageParser Settings

The default CS Message Parser have the following setting (pkimessage variants of the key is accepted for backward compability, see section for PKI Messages):

|===
|Key |Description |Default value 

|csmessage.sourceid |Source Id system sending messages, _(Required)_ |No Default 
|csmessage.sign |If generated messages should be signed. |true 
|csmessage.requiresignature |If parsed message has to have a valid signature. |true 
|csmessage.messagenamecatalogue.impl |If custom message name catalogue should be used. |See below 
|===

As default is Default Message Name Catalogue (setting the 'name' element in the message header), The default implementation takes the element name of the payload and sets it as message name. But specific organisations might have their own custom message names.

== SimpleMessageSecurityProvider Settings.

The simple message security provider uses a set of JKS as backend storage of its keys and have
the following settings.

|===
|Key |Description |Default value 

|simplesecurityprovider.signingkeystore.path
|Setting indicating the path to the signing JKS key store _(Required)_
|No Default

|simplesecurityprovider.signingkeystore.password
|Setting indicating the password to the signing key store _(Required)_
|No Default

|simplesecurityprovider.signingkeystore.alias
|The alias of the certificate to use in the signing key store _(Required)_
|No Default

|simplesecurityprovider.decryptkeystore.path
|The path to the decrypt JKS key store (optional, if not set is signing keystore used for both signing and encryption)
|No Default

|simplesecurityprovider.decryptkeystore.password
|The password to the decrypt JKS key store (optional, if not set is signing keystore used for both signing and encryption)
|No Default

|simplesecurityprovider.decryptkeystore.defaultkey.alias
|the alias of the decryption key to use if no specific key is known. (optional, if not set is same as signing keystore alias used.)
|No Default

|simplesecurityprovider.signature.algorithm
|Signature algorithm scheme to use, possible values are: RSAWithSHA256, RSAWithSHA512, ECDSAWithSHA256, ECDSAWithSHA512
|RSAWithSHA256

|simplesecurityprovider.encryption.algorithm
|Encryption algorithm scheme to use, possible values are: RSA_PKCS1_5_WITH_AES128, RSA_OAEP_WITH_AES128, RSA_PKCS1_5_WITH_AES192, RSA_OAEP_WITH_AES192, RSA_PKCS1_5_WITH_AES256, RSA_OAEP_WITH_AES256
|RSA_OAEP_WITH_AES256

|simplesecurityprovider.trustkeystore.type
| The type of trust store used, can be either CA or ENDENTITY depending on trust policy used.
  If CA should the trust store contain the issuers (the entire chain) of a received signing certificate (from other parties) and
  if ENDENTITY it should contain the actual trusted signing certificates.

  If CA is used should settings: simplesecurityprovider.trustkeystore.matchdnfield and
  simplesecurityprovider.trustkeystore.matchdnvalue is recommended be set to authorize who can send messages. _(Optional)_

| ENDENTITY

|simplesecurityprovider.trustkeystore.path
|The path to the trust JKS key store _(Required)_
|No Default

|simplesecurityprovider.trustkeystore.password
|The password to the trust JKS key store _(Required)_
|No Default

|simplesecurityprovider.trustkeystore.matchsubject
|Setting used if truststore type is CA and indicates that a subject DN check should be added to authorize the
sender. If setting is false will all messages that is issued by any trusted CA by the configuration be accepted.
_(Optional)_
|true

|simplesecurityprovider.trustkeystore.matchdnfield
|Setting indicating which field in client certificate subject dn that should be matched.
Example "OU","O" or "CN".
_(Required if truststore type is CA and matchsubject is true)_
|No Default

|simplesecurityprovider.trustkeystore.matchdnvalue
|Setting indicating the value that should be matched (case-sensitive) in the subject dn.
Example if set to "frontend" and matchdnfield is "OU" only systems that have a trusted client
certificate with a subjectdn containing "OU=frontend" will be accepted.
_(Required if truststore type is CA and matchsubject is true)_
|No Default

|===

=== Example Configuration using the truststore type CA

First make sure that you have a truststore JKS file that contains the complete chain of all CA certificates
that should be trusted. CS message only contains the end entity certificate.

Then define a policy for your application that all certificate that should be trusted should have for example OU=FRONTEND.

To configure this use the following trust store settings

[source, properties]
------
simplesecurityprovider.trustkeystore.type=CA
simplesecurityprovider.trustkeystore.path=<truststore jks path>
simplesecurityprovider.trustkeystore.password=<password>
simplesecurityprovider.trustkeystore.matchdnfield=OU
simplesecurityprovider.trustkeystore.matchdnvalue=FRONTEND
------

== PKCS11MessageSecurityProvider Settings.

PKCS#11 message security provider supports the use of a hardware security module or smartcard to store cryptographic material and to perform cryptographic operations. The following settings can be used to configure the provider.

|===
|Key |Description |Default value 

|pkcs11securityprovider.library.path
|Path to PKCS#11 library to use when communicating with the hardware token. _(Required)_
|No default

|pkcs11securityprovider.slot
|PKCS#11 Slot to use when connecting to the token. _(Required)_
|No default

|pkcs11securityprovider.slot.password
|Password that is used when logging in to token. _(Required)_
|No default

|pkcs11securityprovider.signingkey.alias
|Alias of key to use for signature operations. If not specified the first key found will be used.
|No default

|pkcs11securityprovider.decryptkey.default.alias
|Alias of default key to use for decryption operations. If not specified the signing key will be used.
|_Sign key alias_

|pkcs11securityprovider.signature.algorithm
|Signature algorithm scheme to use, possible values are: RSAWithSHA256, RSAWithSHA512, ECDSAWithSHA256, ECDSAWithSHA512
|RSAWithSHA256

|pkcs11securityprovider.encryption.algorithm
|Encryption algorithm scheme to use, possible values are: RSA_PKCS1_5_WITH_AES128, RSA_OAEP_WITH_AES128, RSA_PKCS1_5_WITH_AES192, RSA_OAEP_WITH_AES192, RSA_PKCS1_5_WITH_AES256, RSA_OAEP_WITH_AES256
|RSA_OAEP_WITH_AES256

|pkcs11securityprovider.trustkeystore.type
| The type of trust store used, can be either CA or ENDENTITY depending on trust policy used.
If CA should the trust store contain the issuers (the entire chain) of a received signing certificate (from other parties) and
if ENDENTITY it should contain the actual trusted signing certificates.

  If CA is used should settings: simplesecurityprovider.trustkeystore.matchdnfield and
  simplesecurityprovider.trustkeystore.matchdnvalue is recommended be set to authorize who can send messages. _(Optional)_

| ENDENTITY

|pkcs11securityprovider.trustkeystore.path
|The path to the trust JKS key store _(Required)_
|No Default

|pkcs11securityprovider.trustkeystore.password
|The password to the trust JKS key store _(Required)_
|No Default

|pkcs11securityprovider.trustkeystore.matchsubject
|Setting used if truststore type is CA and indicates that a subject DN check should be added to authorize the
sender. If setting is false will all messages that is issued by any trusted CA by the configuration be accepted.
_(Optional)_
|true

|pkcs11securityprovider.trustkeystore.matchdnfield
|Setting indicating which field in client certificate subject dn that should be matched.
Example "OU","O" or "CN".
_(Required if truststore type is CA and matchsubject is true)_
|No Default

|pkcs11securityprovider.trustkeystore.matchdnvalue
|Setting indicating the value that should be matched (case-sensitive) in the subject dn.
Example if set to "frontend" and matchdnfield is "OU" only systems that have a trusted client
certificate with a subjectdn containing "OU=frontend" will be accepted.
_(Required if truststore type is CA and matchsubject is true)_
|No Default
|===

== Generating CS 2.0 Messages using payload parser.

After initializing the CS Message Parser it is possible to generate messages using a payload parser. Payload parser can be retrived from se.signatureservice.message.csmessages.PayloadParserRegistry using the method getParser(String namespace). It is also possible to add your own implementations of a payload parser by using the register() method.

For examples on using the payload parser, especially on using it in combination with assertions. See work-flow examples in src/test/groovy/se/signatureservice/messages/csmessages/examples directory.

=== Available Payload Parsers.

The following build in payload parser exists.

Credential Management Payload Parser, to generate credential management messages, See se.signatureservice.message.credmanagement.CredManagementPayloadParser

System Configuration Payload Parser to generate system configuration messages, see se.signatureservice.message.sysconfig.SysConfigPayloadParser

Assertion Payload Parser to generate assertions inserted into other payload messages, see se.signatureservice.message.assertion.AssertionPayloadParser

== DefaultCSMessageParser Settings

For the DefaultPKIMessageParser also exists the following settings:

|===
|Key |Description |Default value 

|pkimessage.sourceid |Source Id system sending messages, _(Required)_ |No Default 
|pkimessage.sign |If generated messages should be signed. |true 
|pkimessage.requiresignature |If parsed message has to have a valid signature. |true 
|pkimessage.messagenamecatalogue.impl |If custom message name catalogue should be used. |See below 
|===

== For Developers of this API

This is a maven project, just check-it out and build with mvn 2 and java 6 +:

Main command to build a binary distribution is:

== Other commands:

To clean:

[source]
----
mvn clean
----

To compile:

[source]
----
mvn compile
----

To test:

[source]
----
mvn test
----

To package (This generates both a binary and source distribution):

[source]
----
mvn package
----

To build site:

[source]
----
mvn site
----

To build site with code coverage report (integration tests must have been setup first):

[source]
----
mvn clean verify site -Pclover.report
----

== How to generate JAXB Class from XSD and Episode files

All XSD and episode files is in src/main/resources, episode files is to link existing classes from imported schemas such as xmldsig without
having to generate new classes. To generate use the following command (for multiple episode files use multible -b options)

[source]
----
xjc -d 'outputdir' 'xsd schema file' -p 'package name' -extension -b src/main/resources/'filename' -b src/main/resources/'filename' -disableXmlSecurity
----

For example:

[source]
----
xjc -d src/main/java src/main/resources/credmanagement_schema2_0.xsd -p se.signatureservice.message.credmanagement.jaxb  -extension -b src/main/resources/csmessage-episode-jaxbbindings.xml -b src/main/resources/xmldsig-episode-jaxbbindings.xml -disableXmlSecurity
----

When generating jaxb code is usually not the correct xml prefixes set, this has to be configured manually in package-info.java class. Remember that when
regenerating the code using xjc is this information overwritten.

To save the result in a separate episode file for generation of dependencies add the parameter -episode 'filename'.

== Eclipse notes

Import the project with a eclipse supporting maven 2 and almost everything should be set-up
automatically, only add src/test/groovy as source folder and you should be ready to go.