//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 07:14:04 AM CEST 
//


package org.certificateservices.messages.authorization.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TokenTypePermissionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TokenTypePermissionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALL"/>
 *     &lt;enumeration value="VIEW"/>
 *     &lt;enumeration value="VIEWANDMONITOR"/>
 *     &lt;enumeration value="MODIFYANDISSUE"/>
 *     &lt;enumeration value="CHANGESTATUS"/>
 *     &lt;enumeration value="PUTONHOLD"/>
 *     &lt;enumeration value="DELETE"/>
 *     &lt;enumeration value="REQUEST"/>
 *     &lt;enumeration value="BATCHUPDATE"/>
 *     &lt;enumeration value="EXPORT"/>
 *     &lt;enumeration value="IMPORT"/>
 *     &lt;enumeration value="UNBLOCK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TokenTypePermissionType")
@XmlEnum
public enum TokenTypePermissionType {

    ALL,
    VIEW,
    VIEWANDMONITOR,
    MODIFYANDISSUE,
    CHANGESTATUS,
    PUTONHOLD,
    DELETE,
    RECOVERKEYS,
    REQUEST,
    BATCHUPDATE,
    EXPORT,
    IMPORT,
    UNBLOCK;

    public String value() {
        return name();
    }

    public static TokenTypePermissionType fromValue(String v) {
        return valueOf(v);
    }

}
