//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.08 at 02:10:50 PM CEST 
//


package org.signatureservice.messages.credmanagement.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CredentialFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CredentialFilter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="credentialTypeFilters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="credentialTypeFilter" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="credentialType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
 *                             &lt;element name="credentialSubType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="credentialSerialNumberFilters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="credentialSerialNumberFilter" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="issuerId" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *                             &lt;element name="serialNumber" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="isNot" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CredentialFilter", propOrder = {
    "credentialTypeFilters",
    "credentialSerialNumberFilters"
})
public class CredentialFilter {

    protected CredentialFilter.CredentialTypeFilters credentialTypeFilters;
    protected CredentialFilter.CredentialSerialNumberFilters credentialSerialNumberFilters;

    /**
     * Gets the value of the credentialTypeFilters property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialFilter.CredentialTypeFilters }
     *     
     */
    public CredentialFilter.CredentialTypeFilters getCredentialTypeFilters() {
        return credentialTypeFilters;
    }

    /**
     * Sets the value of the credentialTypeFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialFilter.CredentialTypeFilters }
     *     
     */
    public void setCredentialTypeFilters(CredentialFilter.CredentialTypeFilters value) {
        this.credentialTypeFilters = value;
    }

    /**
     * Gets the value of the credentialSerialNumberFilters property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialFilter.CredentialSerialNumberFilters }
     *     
     */
    public CredentialFilter.CredentialSerialNumberFilters getCredentialSerialNumberFilters() {
        return credentialSerialNumberFilters;
    }

    /**
     * Sets the value of the credentialSerialNumberFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialFilter.CredentialSerialNumberFilters }
     *     
     */
    public void setCredentialSerialNumberFilters(CredentialFilter.CredentialSerialNumberFilters value) {
        this.credentialSerialNumberFilters = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="credentialSerialNumberFilter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="issuerId" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
     *                   &lt;element name="serialNumber" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="isNot" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "credentialSerialNumberFilter"
    })
    public static class CredentialSerialNumberFilters {

        protected List<CredentialFilter.CredentialSerialNumberFilters.CredentialSerialNumberFilter> credentialSerialNumberFilter;

        /**
         * Gets the value of the credentialSerialNumberFilter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the credentialSerialNumberFilter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCredentialSerialNumberFilter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CredentialFilter.CredentialSerialNumberFilters.CredentialSerialNumberFilter }
         * 
         * 
         */
        public List<CredentialFilter.CredentialSerialNumberFilters.CredentialSerialNumberFilter> getCredentialSerialNumberFilter() {
            if (credentialSerialNumberFilter == null) {
                credentialSerialNumberFilter = new ArrayList<CredentialFilter.CredentialSerialNumberFilters.CredentialSerialNumberFilter>();
            }
            return this.credentialSerialNumberFilter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="issuerId" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
         *         &lt;element name="serialNumber" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
         *       &lt;/sequence>
         *       &lt;attribute name="isNot" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "issuerId",
            "serialNumber"
        })
        public static class CredentialSerialNumberFilter {

            @XmlElement(required = true)
            protected String issuerId;
            @XmlElement(required = true)
            protected String serialNumber;
            @XmlAttribute(name = "isNot")
            protected Boolean isNot;

            /**
             * Gets the value of the issuerId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIssuerId() {
                return issuerId;
            }

            /**
             * Sets the value of the issuerId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIssuerId(String value) {
                this.issuerId = value;
            }

            /**
             * Gets the value of the serialNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerialNumber() {
                return serialNumber;
            }

            /**
             * Sets the value of the serialNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerialNumber(String value) {
                this.serialNumber = value;
            }

            /**
             * Gets the value of the isNot property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isIsNot() {
                if (isNot == null) {
                    return false;
                } else {
                    return isNot;
                }
            }

            /**
             * Sets the value of the isNot property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIsNot(Boolean value) {
                this.isNot = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="credentialTypeFilter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="credentialType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
     *                   &lt;element name="credentialSubType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "credentialTypeFilter"
    })
    public static class CredentialTypeFilters {

        protected List<CredentialFilter.CredentialTypeFilters.CredentialTypeFilter> credentialTypeFilter;

        /**
         * Gets the value of the credentialTypeFilter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the credentialTypeFilter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCredentialTypeFilter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CredentialFilter.CredentialTypeFilters.CredentialTypeFilter }
         * 
         * 
         */
        public List<CredentialFilter.CredentialTypeFilters.CredentialTypeFilter> getCredentialTypeFilter() {
            if (credentialTypeFilter == null) {
                credentialTypeFilter = new ArrayList<CredentialFilter.CredentialTypeFilters.CredentialTypeFilter>();
            }
            return this.credentialTypeFilter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="credentialType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
         *         &lt;element name="credentialSubType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "credentialType",
            "credentialSubType"
        })
        public static class CredentialTypeFilter {

            protected String credentialType;
            protected String credentialSubType;

            /**
             * Gets the value of the credentialType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCredentialType() {
                return credentialType;
            }

            /**
             * Sets the value of the credentialType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCredentialType(String value) {
                this.credentialType = value;
            }

            /**
             * Gets the value of the credentialSubType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCredentialSubType() {
                return credentialSubType;
            }

            /**
             * Sets the value of the credentialSubType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCredentialSubType(String value) {
                this.credentialSubType = value;
            }

        }

    }

}
