//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 11:55:56 AM CEST 
//


package org.signatureservice.messages.credmanagement.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.signatureservice.messages.csmessages.jaxb.CSResponse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSResponse">
 *       &lt;sequence>
 *         &lt;element name="isIssuer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isIssuer"
})
@XmlRootElement(name = "IsIssuerResponse")
public class IsIssuerResponse
    extends CSResponse
{

    protected boolean isIssuer;

    /**
     * Gets the value of the isIssuer property.
     * 
     */
    public boolean isIsIssuer() {
        return isIssuer;
    }

    /**
     * Sets the value of the isIssuer property.
     * 
     */
    public void setIsIssuer(boolean value) {
        this.isIssuer = value;
    }

}
