//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 11:08:13 AM CET 
//


package org.certificateservices.messages.autoenroll.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.certificateservices.messages.csmessages.jaxb.CSRequest;
import org.certificateservices.messages.csmessages.jaxb.Credential;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSRequest">
 *       &lt;sequence>
 *         &lt;element name="type" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="autoEnrollmentProfile" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *                   &lt;element name="currentCredentials" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="credential" type="{http://certificateservices.org/xsd/csmessages2_0}Credential" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type"
})
@XmlRootElement(name = "CheckStatusRequest")
public class CheckStatusRequest
    extends CSRequest
{

    @XmlElement(required = true)
    protected List<CheckStatusRequest.Type> type;

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CheckStatusRequest.Type }
     * 
     * 
     */
    public List<CheckStatusRequest.Type> getType() {
        if (type == null) {
            type = new ArrayList<CheckStatusRequest.Type>();
        }
        return this.type;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="autoEnrollmentProfile" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
     *         &lt;element name="currentCredentials" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="credential" type="{http://certificateservices.org/xsd/csmessages2_0}Credential" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "autoEnrollmentProfile",
        "currentCredentials"
    })
    public static class Type {

        @XmlElement(required = true)
        protected String autoEnrollmentProfile;
        protected CheckStatusRequest.Type.CurrentCredentials currentCredentials;

        /**
         * Gets the value of the autoEnrollmentProfile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutoEnrollmentProfile() {
            return autoEnrollmentProfile;
        }

        /**
         * Sets the value of the autoEnrollmentProfile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutoEnrollmentProfile(String value) {
            this.autoEnrollmentProfile = value;
        }

        /**
         * Gets the value of the currentCredentials property.
         * 
         * @return
         *     possible object is
         *     {@link CheckStatusRequest.Type.CurrentCredentials }
         *     
         */
        public CheckStatusRequest.Type.CurrentCredentials getCurrentCredentials() {
            return currentCredentials;
        }

        /**
         * Sets the value of the currentCredentials property.
         * 
         * @param value
         *     allowed object is
         *     {@link CheckStatusRequest.Type.CurrentCredentials }
         *     
         */
        public void setCurrentCredentials(CheckStatusRequest.Type.CurrentCredentials value) {
            this.currentCredentials = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="credential" type="{http://certificateservices.org/xsd/csmessages2_0}Credential" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "credential"
        })
        public static class CurrentCredentials {

            protected List<Credential> credential;

            /**
             * Gets the value of the credential property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the credential property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCredential().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Credential }
             * 
             * 
             */
            public List<Credential> getCredential() {
                if (credential == null) {
                    credential = new ArrayList<Credential>();
                }
                return this.credential;
            }

        }

    }

}
