//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.05 at 05:18:30 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/01903/v1.4.1#",
xmlns = {
        @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://uri.etsi.org/01903/v1.4.1#", prefix = "xadesv141"),
        @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://uri.etsi.org/01903/v1.3.2#", prefix = "xades"),
        @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix = "ds")}, elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.signatureservice.messages.xades.v141.jaxb;
