//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package se.signatureservice.messages.sweeid2.dssextenstions1_1.jaxb;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignResponseExtensionType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SignResponseExtensionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}ResponseTime"/>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}Request" minOccurs="0"/>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}SignerAssertionInfo" minOccurs="0"/>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}SignatureCertificateChain" minOccurs="0"/>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}OtherResponseInfo" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.1" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignResponseExtensionType", propOrder = {
    "responseTime",
    "request",
    "signerAssertionInfo",
    "signatureCertificateChain",
    "otherResponseInfo"
})
public class SignResponseExtensionType {

    /**
     * The time when the sign response was created.
     * 
     */
    @XmlElement(name = "ResponseTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar responseTime;
    /**
     * An element of type EncodedRequestType with base64Binary base type, holding a
     *                 representation of a complete and signed dss:SignRequest element that is related to this sign response.
     *                 This element MUST be present if signing was successful.
     * 
     */
    @XmlElement(name = "Request")
    protected byte[] request;
    /**
     * An element of type SignerAssertionInfoType holding information about how the signer was
     *                 authenticated by the sign service as well as information about subject attribute values present in the
     *                 SAML assertion authenticating the signer, which was incorporated into the signer certificate. This
     *                 element MUST be present if signing was successful.
     * 
     */
    @XmlElement(name = "SignerAssertionInfo")
    protected SignerAssertionInfoType signerAssertionInfo;
    /**
     * An element of type CertificateChainType holding the signer certificate as well as other
     *                 certificates that may be used to validate the signature. This element MUST be present if signing was
     *                 successful and MUST contain all certificate that are necessary to compile a complete and functional
     *                 signed document.
     * 
     */
    @XmlElement(name = "SignatureCertificateChain")
    protected CertificateChainType signatureCertificateChain;
    /**
     * Optional sign response elements of type AnyType.
     * 
     */
    @XmlElement(name = "OtherResponseInfo")
    protected AnyType otherResponseInfo;
    /**
     * The version of the DSS specification. If absent, the version value defaults to
     *                     "1.1".
     * 
     */
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * The time when the sign response was created.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResponseTime() {
        return responseTime;
    }

    /**
     * Sets the value of the responseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getResponseTime()
     */
    public void setResponseTime(XMLGregorianCalendar value) {
        this.responseTime = value;
    }

    /**
     * An element of type EncodedRequestType with base64Binary base type, holding a
     *                 representation of a complete and signed dss:SignRequest element that is related to this sign response.
     *                 This element MUST be present if signing was successful.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     * @see #getRequest()
     */
    public void setRequest(byte[] value) {
        this.request = value;
    }

    /**
     * An element of type SignerAssertionInfoType holding information about how the signer was
     *                 authenticated by the sign service as well as information about subject attribute values present in the
     *                 SAML assertion authenticating the signer, which was incorporated into the signer certificate. This
     *                 element MUST be present if signing was successful.
     * 
     * @return
     *     possible object is
     *     {@link SignerAssertionInfoType }
     *     
     */
    public SignerAssertionInfoType getSignerAssertionInfo() {
        return signerAssertionInfo;
    }

    /**
     * Sets the value of the signerAssertionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignerAssertionInfoType }
     *     
     * @see #getSignerAssertionInfo()
     */
    public void setSignerAssertionInfo(SignerAssertionInfoType value) {
        this.signerAssertionInfo = value;
    }

    /**
     * An element of type CertificateChainType holding the signer certificate as well as other
     *                 certificates that may be used to validate the signature. This element MUST be present if signing was
     *                 successful and MUST contain all certificate that are necessary to compile a complete and functional
     *                 signed document.
     * 
     * @return
     *     possible object is
     *     {@link CertificateChainType }
     *     
     */
    public CertificateChainType getSignatureCertificateChain() {
        return signatureCertificateChain;
    }

    /**
     * Sets the value of the signatureCertificateChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateChainType }
     *     
     * @see #getSignatureCertificateChain()
     */
    public void setSignatureCertificateChain(CertificateChainType value) {
        this.signatureCertificateChain = value;
    }

    /**
     * Optional sign response elements of type AnyType.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getOtherResponseInfo() {
        return otherResponseInfo;
    }

    /**
     * Sets the value of the otherResponseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     * @see #getOtherResponseInfo()
     */
    public void setOtherResponseInfo(AnyType value) {
        this.otherResponseInfo = value;
    }

    /**
     * The version of the DSS specification. If absent, the version value defaults to
     *                     "1.1".
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVersion()
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
