//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package se.signatureservice.messages.sweeid2.dssextenstions1_1.jaxb;

import java.util.HashMap;
import java.util.Map;
import javax.xml.namespace.QName;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import se.signatureservice.messages.saml2.assertion.jaxb.EncryptedElementType;


/**
 * <p>Java class for SignMessageType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="SignMessageType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}Message"/>
 *         <element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}EncryptedMessage"/>
 *       </choice>
 *       <attribute name="MustShow" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       <attribute name="DisplayEntity" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       <attribute name="MimeType" default="text">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <enumeration value="text/html"/>
 *             <enumeration value="text"/>
 *             <enumeration value="text/markdown"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <anyAttribute processContents='lax' namespace='##other'/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignMessageType", propOrder = {
    "message",
    "encryptedMessage"
})
public class SignMessageType {

    @XmlElement(name = "Message")
    protected byte[] message;
    @XmlElement(name = "EncryptedMessage")
    protected EncryptedElementType encryptedMessage;
    @XmlAttribute(name = "MustShow")
    protected Boolean mustShow;
    @XmlAttribute(name = "DisplayEntity")
    @XmlSchemaType(name = "anyURI")
    protected String displayEntity;
    @XmlAttribute(name = "MimeType")
    protected String mimeType;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<>();

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setMessage(byte[] value) {
        this.message = value;
    }

    /**
     * Gets the value of the encryptedMessage property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptedElementType }
     *     
     */
    public EncryptedElementType getEncryptedMessage() {
        return encryptedMessage;
    }

    /**
     * Sets the value of the encryptedMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptedElementType }
     *     
     */
    public void setEncryptedMessage(EncryptedElementType value) {
        this.encryptedMessage = value;
    }

    /**
     * Gets the value of the mustShow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMustShow() {
        if (mustShow == null) {
            return false;
        } else {
            return mustShow;
        }
    }

    /**
     * Sets the value of the mustShow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMustShow(Boolean value) {
        this.mustShow = value;
    }

    /**
     * Gets the value of the displayEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayEntity() {
        return displayEntity;
    }

    /**
     * Sets the value of the displayEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayEntity(String value) {
        this.displayEntity = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeType() {
        if (mimeType == null) {
            return "text";
        } else {
            return mimeType;
        }
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
