//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.23 at 02:26:35 PM CEST 
//


package org.signatureservice.messages.pkimessages.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IssueTokenCredentialsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IssueTokenCredentialsResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/pkimessages1_0}PKIResponse">
 *       &lt;sequence>
 *         &lt;element name="tokenRequest" type="{http://certificateservices.org/xsd/pkimessages1_0}TokenRequest"/>
 *         &lt;element name="credentials" type="{http://certificateservices.org/xsd/pkimessages1_0}Credential" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IssueTokenCredentialsResponse", propOrder = {
    "tokenRequest",
    "credentials",
    "revokedCredentials"
})
public class IssueTokenCredentialsResponse
    extends PKIResponse
{

    @XmlElement(required = true)
    protected TokenRequest tokenRequest;
    @XmlElement(required = true)
    protected IssueTokenCredentialsResponse.Credentials credentials;
    protected IssueTokenCredentialsResponse.Credentials revokedCredentials;

    /**
     * Gets the value of the tokenRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TokenRequest }
     *     
     */
    public TokenRequest getTokenRequest() {
        return tokenRequest;
    }

    /**
     * Sets the value of the tokenRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenRequest }
     *     
     */
    public void setTokenRequest(TokenRequest value) {
        this.tokenRequest = value;
    }


    
    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link IssueTokenCredentialsResponse.Credentials }
     *     
     */
    public IssueTokenCredentialsResponse.Credentials getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueTokenCredentialsResponse.Credentials }
     *     
     */
    public void setCredentials(IssueTokenCredentialsResponse.Credentials value) {
        this.credentials = value;
    }
    
    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link IssueTokenCredentialsResponse.Credentials }
     *     
     */
    public IssueTokenCredentialsResponse.Credentials getRevokedCredentials() {
        return revokedCredentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueTokenCredentialsResponse.Credentials }
     *     
     */
    public void setRevokedCredentials(IssueTokenCredentialsResponse.Credentials value) {
        this.revokedCredentials = value;
    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="credentialRequest" type="{http://certificateservices.org/xsd/pkimessages1_0}CredentialRequest" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "credential"
    })
    public static class Credentials {

        @XmlElement(required = true)
        protected List<Credential> credential;

        /**
         * Gets the value of the credential property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the credentialRequest property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCredential().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Credential }
         * 
         * 
         */
        public List<Credential> getCredential() {
            if (credential == null) {
                credential = new ArrayList<Credential>();
            }
            return this.credential;
        }

    }

}
