//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 09:13:09 AM CEST 
//


package org.signatureservice.messages.v2x.backend.jaxb;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.v2x.backend.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.v2x.backend.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignCertResponse }
     * 
     */
    public SignCertResponse createSignCertResponse() {
        return new SignCertResponse();
    }

    /**
     * Create an instance of {@link BaseResponseType }
     * 
     */
    public BaseResponseType createBaseResponseType() {
        return new BaseResponseType();
    }

    /**
     * Create an instance of {@link SignCertRequest }
     * 
     */
    public SignCertRequest createSignCertRequest() {
        return new SignCertRequest();
    }

    /**
     * Create an instance of {@link SignErrorRequest }
     * 
     */
    public SignErrorRequest createSignErrorRequest() {
        return new SignErrorRequest();
    }

    /**
     * Create an instance of {@link SignErrorResponse }
     * 
     */
    public SignErrorResponse createSignErrorResponse() {
        return new SignErrorResponse();
    }

}
