//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 09:13:09 AM CEST 
//


package org.signatureservice.messages.v2x.backend.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.signatureservice.messages.csmessages.jaxb.CSRequest;
import org.signatureservice.messages.v2x.registration.jaxb.RegionsType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSRequest">
 *       &lt;sequence>
 *         &lt;element name="canonicalId" type="{http://certificateservices.org/xsd/v2x_registration_2_0}CanonicalIdType"/>
 *         &lt;element name="caId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assuranceLevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="confidenceLevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="validityUnit" type="{http://certificateservices.org/xsd/v2x_backend_2_0}ValidityUnitType" minOccurs="0"/>
 *         &lt;element name="validityDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="profileName" type="{http://certificateservices.org/xsd/v2x_registration_2_0}ProfileNameType"/>
 *         &lt;element name="regions" type="{http://certificateservices.org/xsd/v2x_registration_2_0}RegionsType" minOccurs="0"/>
 *         &lt;element name="publicVerificationKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="publicEncryptionKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="requestHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "canonicalId",
    "caId",
    "assuranceLevel",
    "confidenceLevel",
    "validityUnit",
    "validityDuration",
    "profileName",
    "regions",
    "publicVerificationKey",
    "publicEncryptionKey",
    "requestHash"
})
@XmlRootElement(name = "SignCertRequest")
public class SignCertRequest
    extends CSRequest
{

    @XmlElement(required = true)
    protected String canonicalId;
    @XmlElement(required = true)
    protected String caId;
    protected Integer assuranceLevel;
    protected Integer confidenceLevel;
    @XmlSchemaType(name = "string")
    protected ValidityUnitType validityUnit;
    protected Integer validityDuration;
    @XmlElement(required = true)
    protected String profileName;
    protected RegionsType regions;
    @XmlElement(required = true)
    protected byte[] publicVerificationKey;
    protected byte[] publicEncryptionKey;
    @XmlElement(required = true)
    protected byte[] requestHash;

    /**
     * Gets the value of the canonicalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanonicalId() {
        return canonicalId;
    }

    /**
     * Sets the value of the canonicalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanonicalId(String value) {
        this.canonicalId = value;
    }

    /**
     * Gets the value of the caId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaId() {
        return caId;
    }

    /**
     * Sets the value of the caId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaId(String value) {
        this.caId = value;
    }

    /**
     * Gets the value of the assuranceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAssuranceLevel() {
        return assuranceLevel;
    }

    /**
     * Sets the value of the assuranceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAssuranceLevel(Integer value) {
        this.assuranceLevel = value;
    }

    /**
     * Gets the value of the confidenceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConfidenceLevel() {
        return confidenceLevel;
    }

    /**
     * Sets the value of the confidenceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConfidenceLevel(Integer value) {
        this.confidenceLevel = value;
    }

    /**
     * Gets the value of the validityUnit property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityUnitType }
     *     
     */
    public ValidityUnitType getValidityUnit() {
        return validityUnit;
    }

    /**
     * Sets the value of the validityUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityUnitType }
     *     
     */
    public void setValidityUnit(ValidityUnitType value) {
        this.validityUnit = value;
    }

    /**
     * Gets the value of the validityDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValidityDuration() {
        return validityDuration;
    }

    /**
     * Sets the value of the validityDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValidityDuration(Integer value) {
        this.validityDuration = value;
    }

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsType }
     *     
     */
    public RegionsType getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsType }
     *     
     */
    public void setRegions(RegionsType value) {
        this.regions = value;
    }

    /**
     * Gets the value of the publicVerificationKey property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPublicVerificationKey() {
        return publicVerificationKey;
    }

    /**
     * Sets the value of the publicVerificationKey property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPublicVerificationKey(byte[] value) {
        this.publicVerificationKey = value;
    }

    /**
     * Gets the value of the publicEncryptionKey property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPublicEncryptionKey() {
        return publicEncryptionKey;
    }

    /**
     * Sets the value of the publicEncryptionKey property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPublicEncryptionKey(byte[] value) {
        this.publicEncryptionKey = value;
    }

    /**
     * Gets the value of the requestHash property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRequestHash() {
        return requestHash;
    }

    /**
     * Sets the value of the requestHash property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRequestHash(byte[] value) {
        this.requestHash = value;
    }

}
