//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 10:40:08 AM CEST 
//


package org.certificateservices.messages.keystoremgmt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.certificateservices.messages.csmessages.jaxb.CSResponse;
import org.certificateservices.messages.csmessages.jaxb.CredentialRequest;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSResponse">
 *       &lt;sequence>
 *         &lt;element name="credentialRequest" type="{http://certificateservices.org/xsd/csmessages2_0}CredentialRequest"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credentialRequest"
})
@XmlRootElement(name = "GenerateCredentialRequestResponse", namespace = "http://certificateservices.org/xsd/keystoremgmt2_0")
public class GenerateCredentialRequestResponse
    extends CSResponse
{

    @XmlElement(namespace = "http://certificateservices.org/xsd/keystoremgmt2_0", required = true)
    protected CredentialRequest credentialRequest;

    /**
     * Gets the value of the credentialRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialRequest }
     *     
     */
    public CredentialRequest getCredentialRequest() {
        return credentialRequest;
    }

    /**
     * Sets the value of the credentialRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialRequest }
     *     
     */
    public void setCredentialRequest(CredentialRequest value) {
        this.credentialRequest = value;
    }

}
