//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 10:40:08 AM CEST 
//


package org.certificateservices.messages.keystoremgmt.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KeyStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PENDINGCERTIFICATE"/>
 *     &lt;enumeration value="CERTIFIED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KeyStatus", namespace = "http://certificateservices.org/xsd/keystoremgmt2_0")
@XmlEnum
public enum KeyStatus {

    PENDINGCERTIFICATE,
    CERTIFIED;

    public String value() {
        return name();
    }

    public static KeyStatus fromValue(String v) {
        return valueOf(v);
    }

}
