//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.20 at 10:25:51 AM CET 
//


package org.certificateservices.messages.signrequest.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.signrequest.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.signrequest.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPubKeyResponse }
     * 
     */
    public GetPubKeyResponse createGetPubKeyResponse() {
        return new GetPubKeyResponse();
    }

    /**
     * Create an instance of {@link SignRequest }
     * 
     */
    public SignRequest createSignRequest() {
        return new SignRequest();
    }

    /**
     * Create an instance of {@link SignResponse }
     * 
     */
    public SignResponse createSignResponse() {
        return new SignResponse();
    }

    /**
     * Create an instance of {@link GetPubKeyRequest }
     * 
     */
    public GetPubKeyRequest createGetPubKeyRequest() {
        return new GetPubKeyRequest();
    }

    /**
     * Create an instance of {@link GetPubKeyResponseTask }
     * 
     */
    public GetPubKeyResponseTask createGetPubKeyResponseTask() {
        return new GetPubKeyResponseTask();
    }

    /**
     * Create an instance of {@link GetPubKeyRequestTask }
     * 
     */
    public GetPubKeyRequestTask createGetPubKeyRequestTask() {
        return new GetPubKeyRequestTask();
    }

    /**
     * Create an instance of {@link GetPubKeyResponse.GetPubKeyResponseTasks }
     * 
     */
    public GetPubKeyResponse.GetPubKeyResponseTasks createGetPubKeyResponseGetPubKeyResponseTasks() {
        return new GetPubKeyResponse.GetPubKeyResponseTasks();
    }

    /**
     * Create an instance of {@link SignRequest.SignRequestTasks }
     * 
     */
    public SignRequest.SignRequestTasks createSignRequestSignRequestTasks() {
        return new SignRequest.SignRequestTasks();
    }

    /**
     * Create an instance of {@link SignResponse.SignResponseTasks }
     * 
     */
    public SignResponse.SignResponseTasks createSignResponseSignResponseTasks() {
        return new SignResponse.SignResponseTasks();
    }

    /**
     * Create an instance of {@link GetPubKeyRequest.GetPubKeyRequestTasks }
     * 
     */
    public GetPubKeyRequest.GetPubKeyRequestTasks createGetPubKeyRequestGetPubKeyRequestTasks() {
        return new GetPubKeyRequest.GetPubKeyRequestTasks();
    }

    /**
     * Create an instance of {@link SignResponseTask }
     * 
     */
    public SignResponseTask createSignResponseTask() {
        return new SignResponseTask();
    }

    /**
     * Create an instance of {@link SignRequestTask }
     * 
     */
    public SignRequestTask createSignRequestTask() {
        return new SignRequestTask();
    }

    /**
     * Create an instance of {@link CertificateChainType }
     * 
     */
    public CertificateChainType createCertificateChainType() {
        return new CertificateChainType();
    }

    /**
     * Create an instance of {@link GetPubKeyResponseTask.Attributes }
     * 
     */
    public GetPubKeyResponseTask.Attributes createGetPubKeyResponseTaskAttributes() {
        return new GetPubKeyResponseTask.Attributes();
    }

    /**
     * Create an instance of {@link org.certificateservices.messages.signrequest.jaxb.BaseSignTask.Attributes }
     * 
     */
    public org.certificateservices.messages.signrequest.jaxb.BaseSignTask.Attributes createBaseSignTaskAttributes() {
        return new org.certificateservices.messages.signrequest.jaxb.BaseSignTask.Attributes();
    }

    /**
     * Create an instance of {@link GetPubKeyRequestTask.Attributes }
     * 
     */
    public GetPubKeyRequestTask.Attributes createGetPubKeyRequestTaskAttributes() {
        return new GetPubKeyRequestTask.Attributes();
    }

}
