//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 03:06:39 PM CEST 
//


package org.certificateservices.messages.hardtoken.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tokenType" type="{http://certificateservices.org/xsd/hardtoken}notemptystring"/>
 *         &lt;element name="tokenClass" type="{http://certificateservices.org/xsd/hardtoken}notemptystring"/>
 *         &lt;element name="serialNumber" type="{http://certificateservices.org/xsd/hardtoken}notemptystring"/>
 *         &lt;element name="copyOfSN" type="{http://certificateservices.org/xsd/hardtoken}notemptystring"/>
 *         &lt;element name="copies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="copy" type="{http://certificateservices.org/xsd/hardtoken}notemptystring" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pinDatas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pin" type="{http://certificateservices.org/xsd/hardtoken}PINData" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="supportsRemoteUnblock" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="encKeyKeyRecoverable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="modifyTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://certificateservices.org/xsd/hardtoken}notemptystring" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tokenType",
    "tokenClass",
    "tokenImplementation",
    "serialNumber",
    "copyOfSN",
    "copies",
    "pinDatas",
    "supportsRemoteUnblock",
    "encKeyKeyRecoverable",
    "createTime",
    "modifyTime"
})
@XmlRootElement(name = "HardTokenData")
public class HardTokenData {

    @XmlElement(required = true)
    protected String tokenType;
    @XmlElement(required = true)
    protected String tokenClass;
    protected String tokenImplementation;
    @XmlElement(required = true)
    protected String serialNumber;
    protected String copyOfSN;
    protected HardTokenData.Copies copies;
    @XmlElement(required = true)
    protected HardTokenData.PinDatas pinDatas;
    @XmlElement(defaultValue = "false")
    protected boolean supportsRemoteUnblock;
    @XmlElement(defaultValue = "false")
    protected boolean encKeyKeyRecoverable;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifyTime;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the tokenType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenType() {
        return tokenType;
    }

    /**
     * Sets the value of the tokenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenType(String value) {
        this.tokenType = value;
    }

    /**
     * Gets the value of the tokenClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenClass() {
        return tokenClass;
    }

    /**
     * Sets the value of the tokenClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenClass(String value) {
        this.tokenClass = value;
    }

    /**
     * Gets the value of the tokenImplementation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTokenImplementation() {
        return tokenImplementation;
    }

    /**
     * Sets the value of the tokenImplementation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTokenImplementation(String value) {
        this.tokenImplementation = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the copyOfSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyOfSN() {
        return copyOfSN;
    }

    /**
     * Sets the value of the copyOfSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyOfSN(String value) {
        this.copyOfSN = value;
    }

    /**
     * Gets the value of the copies property.
     * 
     * @return
     *     possible object is
     *     {@link HardTokenData.Copies }
     *     
     */
    public HardTokenData.Copies getCopies() {
        return copies;
    }

    /**
     * Sets the value of the copies property.
     * 
     * @param value
     *     allowed object is
     *     {@link HardTokenData.Copies }
     *     
     */
    public void setCopies(HardTokenData.Copies value) {
        this.copies = value;
    }

    /**
     * Gets the value of the pinDatas property.
     * 
     * @return
     *     possible object is
     *     {@link HardTokenData.PinDatas }
     *     
     */
    public HardTokenData.PinDatas getPinDatas() {
        return pinDatas;
    }

    /**
     * Sets the value of the pinDatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link HardTokenData.PinDatas }
     *     
     */
    public void setPinDatas(HardTokenData.PinDatas value) {
        this.pinDatas = value;
    }

    /**
     * Gets the value of the supportsRemoteUnblock property.
     * 
     */
    public boolean isSupportsRemoteUnblock() {
        return supportsRemoteUnblock;
    }

    /**
     * Sets the value of the supportsRemoteUnblock property.
     * 
     */
    public void setSupportsRemoteUnblock(boolean value) {
        this.supportsRemoteUnblock = value;
    }

    /**
     * Gets the value of the encKeyKeyRecoverable property.
     * 
     */
    public boolean isEncKeyKeyRecoverable() {
        return encKeyKeyRecoverable;
    }

    /**
     * Sets the value of the encKeyKeyRecoverable property.
     * 
     */
    public void setEncKeyKeyRecoverable(boolean value) {
        this.encKeyKeyRecoverable = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateTime(XMLGregorianCalendar value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the modifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifyTime() {
        return modifyTime;
    }

    /**
     * Sets the value of the modifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifyTime(XMLGregorianCalendar value) {
        this.modifyTime = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="copy" type="{http://certificateservices.org/xsd/hardtoken}notemptystring" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "copy"
    })
    public static class Copies {

        protected List<String> copy;

        /**
         * Gets the value of the copy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the copy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCopy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCopy() {
            if (copy == null) {
                copy = new ArrayList<String>();
            }
            return this.copy;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pin" type="{http://certificateservices.org/xsd/hardtoken}PINData" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pin"
    })
    public static class PinDatas {

        @XmlElement(required = true)
        protected List<PINData> pin;

        /**
         * Gets the value of the pin property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pin property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPin().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PINData }
         * 
         * 
         */
        public List<PINData> getPin() {
            if (pin == null) {
                pin = new ArrayList<PINData>();
            }
            return this.pin;
        }

    }

}
