//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 04:03:45 PM CEST 
//


package org.certificateservices.messages.hardtoken.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.hardtoken.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

   
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.hardtoken.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HardTokenData }
     * 
     */
    public HardTokenData createHardTokenData() {
        return new HardTokenData();
    }

    /**
     * Create an instance of {@link HardTokenData.Copies }
     * 
     */
    public HardTokenData.Copies createHardTokenDataCopies() {
        return new HardTokenData.Copies();
    }

    /**
     * Create an instance of {@link HardTokenData.PinDatas }
     * 
     */
    public HardTokenData.PinDatas createHardTokenDataPinDatas() {
        return new HardTokenData.PinDatas();
    }


    /**
     * Create an instance of {@link PINData }
     * 
     */
    public PINData createPINData() {
        return new PINData();
    }


}
