//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:35:43 PM MSK 
//


package org.signatureservice.messages.csagent.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.signatureservice.messages.csmessages.jaxb.CSResponse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSResponse">
 *       &lt;sequence>
 *         &lt;element name="unknownCredentials" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="h" type="{http://certificateservices.org/xsd/csmessages2_0}between1and250string" maxOccurs="100" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unknownCredentials"
})
@XmlRootElement(name = "DiscoveredCredentialsResponse")
public class DiscoveredCredentialsResponse
    extends CSResponse
{

    protected DiscoveredCredentialsResponse.UnknownCredentials unknownCredentials;

    /**
     * Gets the value of the unknownCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link DiscoveredCredentialsResponse.UnknownCredentials }
     *     
     */
    public DiscoveredCredentialsResponse.UnknownCredentials getUnknownCredentials() {
        return unknownCredentials;
    }

    /**
     * Sets the value of the unknownCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscoveredCredentialsResponse.UnknownCredentials }
     *     
     */
    public void setUnknownCredentials(DiscoveredCredentialsResponse.UnknownCredentials value) {
        this.unknownCredentials = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="h" type="{http://certificateservices.org/xsd/csmessages2_0}between1and250string" maxOccurs="100" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "h"
    })
    public static class UnknownCredentials {

        protected List<String> h;

        /**
         * Gets the value of the h property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the h property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getH().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getH() {
            if (h == null) {
                h = new ArrayList<String>();
            }
            return this.h;
        }

    }

}
