//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:35:43 PM MSK 
//


package org.signatureservice.messages.csagent.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiscoveredCredentialData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscoveredCredentialData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/cs_agent_protocol2_0}DiscoveredCredential">
 *       &lt;sequence>
 *         &lt;element name="ct" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
 *         &lt;element name="c" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscoveredCredentialData", propOrder = {
    "ct",
    "c"
})
public class DiscoveredCredentialData
    extends DiscoveredCredential
{

    @XmlElement(defaultValue = "x509certificate")
    protected String ct;
    @XmlElement(required = true)
    protected byte[] c;

    /**
     * Gets the value of the ct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCt() {
        return ct;
    }

    /**
     * Sets the value of the ct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCt(String value) {
        this.ct = value;
    }

    /**
     * Gets the value of the c property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setC(byte[] value) {
        this.c = value;
    }

}
