//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:35:43 PM MSK 
//


package org.signatureservice.messages.csagent.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.csagent.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.csagent.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DiscoveredCredentialsResponse }
     * 
     */
    public DiscoveredCredentialsResponse createDiscoveredCredentialsResponse() {
        return new DiscoveredCredentialsResponse();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialDataRequest }
     * 
     */
    public DiscoveredCredentialDataRequest createDiscoveredCredentialDataRequest() {
        return new DiscoveredCredentialDataRequest();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialsRequest }
     * 
     */
    public DiscoveredCredentialsRequest createDiscoveredCredentialsRequest() {
        return new DiscoveredCredentialsRequest();
    }

    /**
     * Create an instance of {@link DiscoveredCredential }
     * 
     */
    public DiscoveredCredential createDiscoveredCredential() {
        return new DiscoveredCredential();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialsResponse.UnknownCredentials }
     * 
     */
    public DiscoveredCredentialsResponse.UnknownCredentials createDiscoveredCredentialsResponseUnknownCredentials() {
        return new DiscoveredCredentialsResponse.UnknownCredentials();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialDataRequest.DiscoveredCredentialData }
     * 
     */
    public DiscoveredCredentialDataRequest.DiscoveredCredentialData createDiscoveredCredentialDataRequestDiscoveredCredentialData() {
        return new DiscoveredCredentialDataRequest.DiscoveredCredentialData();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialsRequest.DiscoveredCredentials }
     * 
     */
    public DiscoveredCredentialsRequest.DiscoveredCredentials createDiscoveredCredentialsRequestDiscoveredCredentials() {
        return new DiscoveredCredentialsRequest.DiscoveredCredentials();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialDataResponse }
     * 
     */
    public DiscoveredCredentialDataResponse createDiscoveredCredentialDataResponse() {
        return new DiscoveredCredentialDataResponse();
    }

    /**
     * Create an instance of {@link DiscoveredCredentialData }
     * 
     */
    public DiscoveredCredentialData createDiscoveredCredentialData() {
        return new DiscoveredCredentialData();
    }

    /**
     * Create an instance of {@link DiscoveredCredential.As }
     * 
     */
    public DiscoveredCredential.As createDiscoveredCredentialAs() {
        return new DiscoveredCredential.As();
    }

}
