//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 11:16:33 AM CEST 
//


package org.signatureservice.messages.csexport.data.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TokenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TokenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="32"/>
 *               &lt;pattern value="[a-z0-9_\-]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="displayName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="description" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="5000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="credentialProviderName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="uniqueIdPrefix" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fieldUsedAsUserUniqueId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="255"/>
 *               &lt;pattern value="[a-z0-9_\-\.]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fieldUsedAsUserDisplayName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="32"/>
 *               &lt;pattern value="[a-z0-9_\-\.]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="organisations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="organisation" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenTypeOrganisation" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allOrganisations" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="useInGenerateTab" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isMonitoredByDefault" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="useDepartments" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="useExpireDateField" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="useValidFromDateField" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="editableFields" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="isSuspendable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="applyLifeCycleRulesInManualGeneration" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="fieldConstraints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fieldConstraint" type="{http://certificateservices.org/xsd/csexport_data_1_0}FieldConstraint" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="credentialConstraints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="credentialConstraint" type="{http://certificateservices.org/xsd/csexport_data_1_0}CredentialConstraint" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="keySpecConstraints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="keySpecConstraint" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tokenContainerConstraints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tokenContainerConstraint" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenContainerConstraint" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allowedCSRSignatureAlgorithms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="allowedCSRSignatureAlgorithm" type="{http://certificateservices.org/xsd/csexport_data_1_0}AllowedCSRSignatureAlgorithm" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="certificateChainOption" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="keystoreTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="keystoreType" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenContainerInfoEx" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tokenTypeLifeCycleRules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tokenTypeLifeCycleRule" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenTypeLifeCycleRule" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="validityRestrictions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="validityRestriction" type="{http://certificateservices.org/xsd/csexport_data_1_0}ValidityRestriction" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TokenType", propOrder = {
    "name",
    "displayName",
    "description",
    "credentialProviderName",
    "uniqueIdPrefix",
    "fieldUsedAsUserUniqueId",
    "fieldUsedAsUserDisplayName",
    "organisations",
    "allOrganisations",
    "useInGenerateTab",
    "isMonitoredByDefault",
    "useDepartments",
    "useExpireDateField",
    "useValidFromDateField",
    "editableFields",
    "isSuspendable",
    "applyLifeCycleRulesInManualGeneration",
    "fieldConstraints",
    "credentialConstraints",
    "keySpecConstraints",
    "tokenContainerConstraints",
    "allowedCSRSignatureAlgorithms",
    "certificateChainOption",
    "keystoreTypes",
    "tokenTypeLifeCycleRules",
    "validityRestrictions"
})
public class TokenType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String displayName;
    protected String description;
    protected String credentialProviderName;
    protected String uniqueIdPrefix;
    protected String fieldUsedAsUserUniqueId;
    protected String fieldUsedAsUserDisplayName;
    protected TokenType.Organisations organisations;
    protected Boolean allOrganisations;
    protected Boolean useInGenerateTab;
    protected boolean isMonitoredByDefault;
    protected boolean useDepartments;
    protected boolean useExpireDateField;
    protected boolean useValidFromDateField;
    protected boolean editableFields;
    protected boolean isSuspendable;
    protected Boolean applyLifeCycleRulesInManualGeneration;
    protected TokenType.FieldConstraints fieldConstraints;
    protected TokenType.CredentialConstraints credentialConstraints;
    protected TokenType.KeySpecConstraints keySpecConstraints;
    protected TokenType.TokenContainerConstraints tokenContainerConstraints;
    protected TokenType.AllowedCSRSignatureAlgorithms allowedCSRSignatureAlgorithms;
    protected String certificateChainOption;
    protected TokenType.KeystoreTypes keystoreTypes;
    protected TokenType.TokenTypeLifeCycleRules tokenTypeLifeCycleRules;
    protected TokenType.ValidityRestrictions validityRestrictions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the credentialProviderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialProviderName() {
        return credentialProviderName;
    }

    /**
     * Sets the value of the credentialProviderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialProviderName(String value) {
        this.credentialProviderName = value;
    }

    /**
     * Gets the value of the uniqueIdPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueIdPrefix() {
        return uniqueIdPrefix;
    }

    /**
     * Sets the value of the uniqueIdPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueIdPrefix(String value) {
        this.uniqueIdPrefix = value;
    }

    /**
     * Gets the value of the fieldUsedAsUserUniqueId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldUsedAsUserUniqueId() {
        return fieldUsedAsUserUniqueId;
    }

    /**
     * Sets the value of the fieldUsedAsUserUniqueId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldUsedAsUserUniqueId(String value) {
        this.fieldUsedAsUserUniqueId = value;
    }

    /**
     * Gets the value of the fieldUsedAsUserDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldUsedAsUserDisplayName() {
        return fieldUsedAsUserDisplayName;
    }

    /**
     * Sets the value of the fieldUsedAsUserDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldUsedAsUserDisplayName(String value) {
        this.fieldUsedAsUserDisplayName = value;
    }

    /**
     * Gets the value of the organisations property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.Organisations }
     *     
     */
    public TokenType.Organisations getOrganisations() {
        return organisations;
    }

    /**
     * Sets the value of the organisations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.Organisations }
     *     
     */
    public void setOrganisations(TokenType.Organisations value) {
        this.organisations = value;
    }

    /**
     * Gets the value of the allOrganisations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllOrganisations() {
        return allOrganisations;
    }

    /**
     * Sets the value of the allOrganisations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllOrganisations(Boolean value) {
        this.allOrganisations = value;
    }

    /**
     * Gets the value of the useInGenerateTab property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseInGenerateTab() {
        return useInGenerateTab;
    }

    /**
     * Sets the value of the useInGenerateTab property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseInGenerateTab(Boolean value) {
        this.useInGenerateTab = value;
    }

    /**
     * Gets the value of the isMonitoredByDefault property.
     * 
     */
    public boolean isIsMonitoredByDefault() {
        return isMonitoredByDefault;
    }

    /**
     * Sets the value of the isMonitoredByDefault property.
     * 
     */
    public void setIsMonitoredByDefault(boolean value) {
        this.isMonitoredByDefault = value;
    }

    /**
     * Gets the value of the useDepartments property.
     * 
     */
    public boolean isUseDepartments() {
        return useDepartments;
    }

    /**
     * Sets the value of the useDepartments property.
     * 
     */
    public void setUseDepartments(boolean value) {
        this.useDepartments = value;
    }

    /**
     * Gets the value of the useExpireDateField property.
     * 
     */
    public boolean isUseExpireDateField() {
        return useExpireDateField;
    }

    /**
     * Sets the value of the useExpireDateField property.
     * 
     */
    public void setUseExpireDateField(boolean value) {
        this.useExpireDateField = value;
    }

    /**
     * Gets the value of the useValidFromDateField property.
     * 
     */
    public boolean isUseValidFromDateField() {
        return useValidFromDateField;
    }

    /**
     * Sets the value of the useValidFromDateField property.
     * 
     */
    public void setUseValidFromDateField(boolean value) {
        this.useValidFromDateField = value;
    }

    /**
     * Gets the value of the editableFields property.
     * 
     */
    public boolean isEditableFields() {
        return editableFields;
    }

    /**
     * Sets the value of the editableFields property.
     * 
     */
    public void setEditableFields(boolean value) {
        this.editableFields = value;
    }

    /**
     * Gets the value of the isSuspendable property.
     * 
     */
    public boolean isIsSuspendable() {
        return isSuspendable;
    }

    /**
     * Sets the value of the isSuspendable property.
     * 
     */
    public void setIsSuspendable(boolean value) {
        this.isSuspendable = value;
    }

    /**
     * Gets the value of the applyLifeCycleRulesInManualGeneration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApplyLifeCycleRulesInManualGeneration() {
        return applyLifeCycleRulesInManualGeneration;
    }

    /**
     * Sets the value of the applyLifeCycleRulesInManualGeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplyLifeCycleRulesInManualGeneration(Boolean value) {
        this.applyLifeCycleRulesInManualGeneration = value;
    }

    /**
     * Gets the value of the fieldConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.FieldConstraints }
     *     
     */
    public TokenType.FieldConstraints getFieldConstraints() {
        return fieldConstraints;
    }

    /**
     * Sets the value of the fieldConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.FieldConstraints }
     *     
     */
    public void setFieldConstraints(TokenType.FieldConstraints value) {
        this.fieldConstraints = value;
    }

    /**
     * Gets the value of the credentialConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.CredentialConstraints }
     *     
     */
    public TokenType.CredentialConstraints getCredentialConstraints() {
        return credentialConstraints;
    }

    /**
     * Sets the value of the credentialConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.CredentialConstraints }
     *     
     */
    public void setCredentialConstraints(TokenType.CredentialConstraints value) {
        this.credentialConstraints = value;
    }

    /**
     * Gets the value of the keySpecConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.KeySpecConstraints }
     *     
     */
    public TokenType.KeySpecConstraints getKeySpecConstraints() {
        return keySpecConstraints;
    }

    /**
     * Sets the value of the keySpecConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.KeySpecConstraints }
     *     
     */
    public void setKeySpecConstraints(TokenType.KeySpecConstraints value) {
        this.keySpecConstraints = value;
    }

    /**
     * Gets the value of the tokenContainerConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.TokenContainerConstraints }
     *     
     */
    public TokenType.TokenContainerConstraints getTokenContainerConstraints() {
        return tokenContainerConstraints;
    }

    /**
     * Sets the value of the tokenContainerConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.TokenContainerConstraints }
     *     
     */
    public void setTokenContainerConstraints(TokenType.TokenContainerConstraints value) {
        this.tokenContainerConstraints = value;
    }

    /**
     * Gets the value of the allowedCSRSignatureAlgorithms property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.AllowedCSRSignatureAlgorithms }
     *     
     */
    public TokenType.AllowedCSRSignatureAlgorithms getAllowedCSRSignatureAlgorithms() {
        return allowedCSRSignatureAlgorithms;
    }

    /**
     * Sets the value of the allowedCSRSignatureAlgorithms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.AllowedCSRSignatureAlgorithms }
     *     
     */
    public void setAllowedCSRSignatureAlgorithms(TokenType.AllowedCSRSignatureAlgorithms value) {
        this.allowedCSRSignatureAlgorithms = value;
    }

    /**
     * Gets the value of the certificateChainOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateChainOption() {
        return certificateChainOption;
    }

    /**
     * Sets the value of the certificateChainOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateChainOption(String value) {
        this.certificateChainOption = value;
    }

    /**
     * Gets the value of the keystoreTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.KeystoreTypes }
     *     
     */
    public TokenType.KeystoreTypes getKeystoreTypes() {
        return keystoreTypes;
    }

    /**
     * Sets the value of the keystoreTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.KeystoreTypes }
     *     
     */
    public void setKeystoreTypes(TokenType.KeystoreTypes value) {
        this.keystoreTypes = value;
    }

    /**
     * Gets the value of the tokenTypeLifeCycleRules property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.TokenTypeLifeCycleRules }
     *     
     */
    public TokenType.TokenTypeLifeCycleRules getTokenTypeLifeCycleRules() {
        return tokenTypeLifeCycleRules;
    }

    /**
     * Sets the value of the tokenTypeLifeCycleRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.TokenTypeLifeCycleRules }
     *     
     */
    public void setTokenTypeLifeCycleRules(TokenType.TokenTypeLifeCycleRules value) {
        this.tokenTypeLifeCycleRules = value;
    }

    /**
     * Gets the value of the validityRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType.ValidityRestrictions }
     *     
     */
    public TokenType.ValidityRestrictions getValidityRestrictions() {
        return validityRestrictions;
    }

    /**
     * Sets the value of the validityRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType.ValidityRestrictions }
     *     
     */
    public void setValidityRestrictions(TokenType.ValidityRestrictions value) {
        this.validityRestrictions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="allowedCSRSignatureAlgorithm" type="{http://certificateservices.org/xsd/csexport_data_1_0}AllowedCSRSignatureAlgorithm" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allowedCSRSignatureAlgorithm"
    })
    public static class AllowedCSRSignatureAlgorithms {

        protected List<String> allowedCSRSignatureAlgorithm;

        /**
         * Gets the value of the allowedCSRSignatureAlgorithm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the allowedCSRSignatureAlgorithm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAllowedCSRSignatureAlgorithm().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAllowedCSRSignatureAlgorithm() {
            if (allowedCSRSignatureAlgorithm == null) {
                allowedCSRSignatureAlgorithm = new ArrayList<String>();
            }
            return this.allowedCSRSignatureAlgorithm;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="credentialConstraint" type="{http://certificateservices.org/xsd/csexport_data_1_0}CredentialConstraint" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "credentialConstraint"
    })
    public static class CredentialConstraints {

        protected List<CredentialConstraint> credentialConstraint;

        /**
         * Gets the value of the credentialConstraint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the credentialConstraint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCredentialConstraint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CredentialConstraint }
         * 
         * 
         */
        public List<CredentialConstraint> getCredentialConstraint() {
            if (credentialConstraint == null) {
                credentialConstraint = new ArrayList<CredentialConstraint>();
            }
            return this.credentialConstraint;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fieldConstraint" type="{http://certificateservices.org/xsd/csexport_data_1_0}FieldConstraint" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldConstraint"
    })
    public static class FieldConstraints {

        protected List<FieldConstraint> fieldConstraint;

        /**
         * Gets the value of the fieldConstraint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldConstraint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldConstraint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FieldConstraint }
         * 
         * 
         */
        public List<FieldConstraint> getFieldConstraint() {
            if (fieldConstraint == null) {
                fieldConstraint = new ArrayList<FieldConstraint>();
            }
            return this.fieldConstraint;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="keySpecConstraint" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keySpecConstraint"
    })
    public static class KeySpecConstraints {

        protected List<String> keySpecConstraint;

        /**
         * Gets the value of the keySpecConstraint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the keySpecConstraint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKeySpecConstraint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getKeySpecConstraint() {
            if (keySpecConstraint == null) {
                keySpecConstraint = new ArrayList<String>();
            }
            return this.keySpecConstraint;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="keystoreType" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenContainerInfoEx" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keystoreType"
    })
    public static class KeystoreTypes {

        protected List<TokenContainerInfoEx> keystoreType;

        /**
         * Gets the value of the keystoreType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the keystoreType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKeystoreType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TokenContainerInfoEx }
         * 
         * 
         */
        public List<TokenContainerInfoEx> getKeystoreType() {
            if (keystoreType == null) {
                keystoreType = new ArrayList<TokenContainerInfoEx>();
            }
            return this.keystoreType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="organisation" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenTypeOrganisation" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organisation"
    })
    public static class Organisations {

        protected List<TokenTypeOrganisation> organisation;

        /**
         * Gets the value of the organisation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the organisation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrganisation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TokenTypeOrganisation }
         * 
         * 
         */
        public List<TokenTypeOrganisation> getOrganisation() {
            if (organisation == null) {
                organisation = new ArrayList<TokenTypeOrganisation>();
            }
            return this.organisation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tokenContainerConstraint" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenContainerConstraint" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tokenContainerConstraint"
    })
    public static class TokenContainerConstraints {

        protected List<String> tokenContainerConstraint;

        /**
         * Gets the value of the tokenContainerConstraint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tokenContainerConstraint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTokenContainerConstraint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTokenContainerConstraint() {
            if (tokenContainerConstraint == null) {
                tokenContainerConstraint = new ArrayList<String>();
            }
            return this.tokenContainerConstraint;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tokenTypeLifeCycleRule" type="{http://certificateservices.org/xsd/csexport_data_1_0}TokenTypeLifeCycleRule" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tokenTypeLifeCycleRule"
    })
    public static class TokenTypeLifeCycleRules {

        protected List<TokenTypeLifeCycleRule> tokenTypeLifeCycleRule;

        /**
         * Gets the value of the tokenTypeLifeCycleRule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tokenTypeLifeCycleRule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTokenTypeLifeCycleRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TokenTypeLifeCycleRule }
         * 
         * 
         */
        public List<TokenTypeLifeCycleRule> getTokenTypeLifeCycleRule() {
            if (tokenTypeLifeCycleRule == null) {
                tokenTypeLifeCycleRule = new ArrayList<TokenTypeLifeCycleRule>();
            }
            return this.tokenTypeLifeCycleRule;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="validityRestriction" type="{http://certificateservices.org/xsd/csexport_data_1_0}ValidityRestriction" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validityRestriction"
    })
    public static class ValidityRestrictions {

        protected List<ValidityRestriction> validityRestriction;

        /**
         * Gets the value of the validityRestriction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the validityRestriction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValidityRestriction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ValidityRestriction }
         * 
         * 
         */
        public List<ValidityRestriction> getValidityRestriction() {
            if (validityRestriction == null) {
                validityRestriction = new ArrayList<ValidityRestriction>();
            }
            return this.validityRestriction;
        }

    }

}
