//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.04 at 04:02:56 PM MSK
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://certificateservices.org/xsd/cs_agent_protocol2_0",
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://certificateservices.org/xsd/cs_agent_protocol2_0", prefix = "a"),
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix = "ds"),
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://certificateservices.org/xsd/csmessages2_0", prefix = "cs")},
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.certificateservices.messages.csagent.jaxb;
