//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.23 at 02:26:35 PM CEST 
//


package org.certificateservices.messages.pkimessages.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservice.ca.pkimessages.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservice.ca.pkimessages.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PKIMessage }
     * 
     */
    public PKIMessage createPKIMessage() {
        return new PKIMessage();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link CredentialRequest }
     * 
     */
    public CredentialRequest createCredentialRequest() {
        return new CredentialRequest();
    }

    /**
     * Create an instance of {@link TokenRequest }
     * 
     */
    public TokenRequest createTokenRequest() {
        return new TokenRequest();
    }

    /**
     * Create an instance of {@link PKIMessage.Payload }
     * 
     */
    public PKIMessage.Payload createPKIMessagePayload() {
        return new PKIMessage.Payload();
    }



    /**
     * Create an instance of {@link GetIssuerCredentialsResponse }
     * 
     */
    public GetIssuerCredentialsResponse createGetIssuerCredentialsResponse() {
        return new GetIssuerCredentialsResponse();
    }

    /**
     * Create an instance of {@link FetchHardTokenDataResponse }
     * 
     */
    public FetchHardTokenDataResponse createFetchHardTokenDataResponse() {
        return new FetchHardTokenDataResponse();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsRequest }
     * 
     */
    public IssueTokenCredentialsRequest createIssueTokenCredentialsRequest() {
        return new IssueTokenCredentialsRequest();
    }

    /**
     * Create an instance of {@link PKIResponse }
     * 
     */
    public PKIResponse createPKIResponse() {
        return new PKIResponse();
    }

    /**
     * Create an instance of {@link CredentialStatusList }
     * 
     */
    public CredentialStatusList createCredentialStatusList() {
        return new CredentialStatusList();
    }

    /**
     * Create an instance of {@link IssueCredentialStatusListRequest }
     * 
     */
    public IssueCredentialStatusListRequest createIssueCredentialStatusListRequest() {
        return new IssueCredentialStatusListRequest();
    }


    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }
    
    /**
     * Create an instance of {@link Originator }
     * 
     */
    public Originator createOriginator() {
        return new Originator();
    }

    /**
     * Create an instance of {@link GetCredentialStatusListResponse }
     * 
     */
    public GetCredentialStatusListResponse createGetCredentialStatusListResponse() {
        return new GetCredentialStatusListResponse();
    }

    /**
     * Create an instance of {@link FetchHardTokenDataRequest }
     * 
     */
    public FetchHardTokenDataRequest createFetchHardTokenDataRequest() {
        return new FetchHardTokenDataRequest();
    }

    /**
     * Create an instance of {@link IssueCredentialStatusListResponse }
     * 
     */
    public IssueCredentialStatusListResponse createIssueCredentialStatusListResponse() {
        return new IssueCredentialStatusListResponse();
    }

    /**
     * Create an instance of {@link RemoveCredentialRequest }
     * 
     */
    public RemoveCredentialRequest createRemoveCredentialRequest() {
        return new RemoveCredentialRequest();
    }

    /**
     * Create an instance of {@link GetCredentialStatusListRequest }
     * 
     */
    public GetCredentialStatusListRequest createGetCredentialStatusListRequest() {
        return new GetCredentialStatusListRequest();
    }

    /**
     * Create an instance of {@link StoreHardTokenDataResponse }
     * 
     */
    public StoreHardTokenDataResponse createStoreHardTokenDataResponse() {
        return new StoreHardTokenDataResponse();
    }

    /**
     * Create an instance of {@link ChangeCredentialStatusRequest }
     * 
     */
    public ChangeCredentialStatusRequest createChangeCredentialStatusRequest() {
        return new ChangeCredentialStatusRequest();
    }

    /**
     * Create an instance of {@link RemoveCredentialResponse }
     * 
     */
    public RemoveCredentialResponse createRemoveCredentialResponse() {
        return new RemoveCredentialResponse();
    }

    /**
     * Create an instance of {@link GetCredentialResponse }
     * 
     */
    public GetCredentialResponse createGetCredentialResponse() {
        return new GetCredentialResponse();
    }

    /**
     * Create an instance of {@link GetIssuerCredentialsRequest }
     * 
     */
    public GetIssuerCredentialsRequest createGetIssuerCredentialsRequest() {
        return new GetIssuerCredentialsRequest();
    }

    /**
     * Create an instance of {@link GetCredentialRequest }
     * 
     */
    public GetCredentialRequest createGetCredentialRequest() {
        return new GetCredentialRequest();
    }

    /**
     * Create an instance of {@link IsIssuerResponse }
     * 
     */
    public IsIssuerResponse createIsIssuerResponse() {
        return new IsIssuerResponse();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsResponse }
     * 
     */
    public IssueTokenCredentialsResponse createIssueTokenCredentialsResponse() {
        return new IssueTokenCredentialsResponse();
    }

    /**
     * Create an instance of {@link IsIssuerRequest }
     * 
     */
    public IsIssuerRequest createIsIssuerRequest() {
        return new IsIssuerRequest();
    }

    /**
     * Create an instance of {@link StoreHardTokenDataRequest }
     * 
     */
    public StoreHardTokenDataRequest createStoreHardTokenDataRequest() {
        return new StoreHardTokenDataRequest();
    }

    /**
     * Create an instance of {@link ChangeCredentialStatusResponse }
     * 
     */
    public ChangeCredentialStatusResponse createChangeCredentialStatusResponse() {
        return new ChangeCredentialStatusResponse();
    }


    /**
     * Create an instance of {@link TokenRequest.CredentialRequests }
     * 
     */
    public TokenRequest.CredentialRequests createCredentialRequests() {
        return new TokenRequest.CredentialRequests();
    }
    
    /**
     * Create an instance of {@link Credential.Attributes }
     * 
     */
    public Credential.Attributes createCredentialAttributes() {
        return new Credential.Attributes();
    }

    /**
     * Create an instance of {@link Credential.Usages }
     * 
     */
    public Credential.Usages createCredentialUsages() {
        return new Credential.Usages();
    }

    /**
     * Create an instance of {@link CredentialRequest.Attributes }
     * 
     */
    public CredentialRequest.Attributes createCredentialRequestAttributes() {
        return new CredentialRequest.Attributes();
    }

    /**
     * Create an instance of {@link TokenRequest.CredentialRequests }
     * 
     */
    public TokenRequest.CredentialRequests createTokenRequestCredentialRequests() {
        return new TokenRequest.CredentialRequests();
    }

    /**
     * Create an instance of {@link TokenRequest.Attributes }
     * 
     */
    public TokenRequest.Attributes createTokenRequestAttributes() {
        return new TokenRequest.Attributes();
    }

 

}
