//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.20 at 06:19:56 PM CEST 
//


package org.certificateservices.messages.authcontsaci1.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SAMLAuthContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SAMLAuthContextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://id.elegnamnden.se/auth-cont/1.0/saci}AuthContextInfo" minOccurs="0"/>
 *         &lt;element ref="{http://id.elegnamnden.se/auth-cont/1.0/saci}IdAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SAMLAuthContextType", propOrder = {
    "authContextInfo",
    "idAttributes"
})
public class SAMLAuthContextType {

    @XmlElement(name = "AuthContextInfo")
    protected AuthContextInfoType authContextInfo;
    @XmlElement(name = "IdAttributes")
    protected IdAttributesType idAttributes;

    /**
     * Gets the value of the authContextInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AuthContextInfoType }
     *     
     */
    public AuthContextInfoType getAuthContextInfo() {
        return authContextInfo;
    }

    /**
     * Sets the value of the authContextInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthContextInfoType }
     *     
     */
    public void setAuthContextInfo(AuthContextInfoType value) {
        this.authContextInfo = value;
    }

    /**
     * Gets the value of the idAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link IdAttributesType }
     *     
     */
    public IdAttributesType getIdAttributes() {
        return idAttributes;
    }

    /**
     * Sets the value of the idAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdAttributesType }
     *     
     */
    public void setIdAttributes(IdAttributesType value) {
        this.idAttributes = value;
    }

}
