//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 10:40:08 AM CEST 
//


package org.signatureservice.messages.keystoremgmt.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.keystoremgmt.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.keystoremgmt.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerateCredentialRequestRequest }
     * 
     */
    public GenerateCredentialRequestRequest createGenerateCredentialRequestRequest() {
        return new GenerateCredentialRequestRequest();
    }

    /**
     * Create an instance of {@link AttachCredentialsRequest }
     * 
     */
    public AttachCredentialsRequest createAttachCredentialsRequest() {
        return new AttachCredentialsRequest();
    }


    /**
     * Create an instance of {@link KeyInfo }
     * 
     */
    public KeyInfo createKeyInfo() {
        return new KeyInfo();
    }

    /**
     * Create an instance of {@link KeyStore }
     * 
     */
    public KeyStore createKeyStore() {
        return new KeyStore();
    }


    /**
     * Create an instance of {@link GenerateCredentialRequestRequest.CredentialRequestParams }
     * 
     */
    public GenerateCredentialRequestRequest.CredentialRequestParams createGenerateCredentialRequestRequestCredentialRequestParams() {
        return new GenerateCredentialRequestRequest.CredentialRequestParams();
    }

    /**
     * Create an instance of {@link AttachCredentialsResponse }
     * 
     */
    public AttachCredentialsResponse createAttachCredentialsResponse() {
        return new AttachCredentialsResponse();
    }


    /**
     * Create an instance of {@link GenerateCredentialRequestResponse }
     * 
     */
    public GenerateCredentialRequestResponse createGenerateCredentialRequestResponse() {
        return new GenerateCredentialRequestResponse();
    }

    /**
     * Create an instance of {@link RemoveKeyRequest }
     * 
     */
    public RemoveKeyRequest createRemoveKeyRequest() {
        return new RemoveKeyRequest();
    }

    /**
     * Create an instance of {@link GetAvailableKeyStoreInfoRequest }
     * 
     */
    public GetAvailableKeyStoreInfoRequest createGetAvailableKeyStoreInfoRequest() {
        return new GetAvailableKeyStoreInfoRequest();
    }

    /**
     * Create an instance of {@link UpdateKeyDescriptionRequest }
     * 
     */
    public UpdateKeyDescriptionRequest createUpdateKeyDescriptionRequest() {
        return new UpdateKeyDescriptionRequest();
    }

    /**
     * Create an instance of {@link UpdateKeyDescriptionResponse }
     * 
     */
    public UpdateKeyDescriptionResponse createUpdateKeyDescriptionResponse() {
        return new UpdateKeyDescriptionResponse();
    }

    /**
     * Create an instance of {@link GetAvailableKeyStoreInfoResponse }
     * 
     */
    public GetAvailableKeyStoreInfoResponse createGetAvailableKeyStoreInfoResponse() {
        return new GetAvailableKeyStoreInfoResponse();
    }

    /**
     * Create an instance of {@link AttachCredentialsRequest.Credentials }
     * 
     */
    public AttachCredentialsRequest.Credentials createAttachCredentialsRequestCredentials() {
        return new AttachCredentialsRequest.Credentials();
    }

    /**
     * Create an instance of {@link RemoveKeyResponse }
     * 
     */
    public RemoveKeyResponse createRemoveKeyResponse() {
        return new RemoveKeyResponse();
    }

    /**
     * Create an instance of {@link CredentialRequestParams }
     * 
     */
    public CredentialRequestParams createCredentialRequestParams() {
        return new CredentialRequestParams();
    }

    /**
     * Create an instance of {@link X509CredentialRequestParams }
     * 
     */
    public X509CredentialRequestParams createX509CredentialRequestParams() {
        return new X509CredentialRequestParams();
    }


}
