//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 03:44:49 PM MSK 
//


package org.certificateservices.messages.saml2.metadata.ui.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import org.certificateservices.messages.saml2.metadata.jaxb.LocalizedNameType;
import org.certificateservices.messages.saml2.metadata.jaxb.LocalizedURIType;
import org.w3c.dom.Element;


/**
 * <p>Java class for UIInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}DisplayName"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}Description"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}Keywords"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}Logo"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}InformationURL"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}PrivacyStatementURL"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIInfoType", propOrder = {
    "displayNameOrDescriptionOrKeywords"
})
public class UIInfoType {

    @XmlElementRefs({
        @XmlElementRef(name = "InformationURL", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DisplayName", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PrivacyStatementURL", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Logo", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Keywords", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Description", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> displayNameOrDescriptionOrKeywords;

    /**
     * Gets the value of the displayNameOrDescriptionOrKeywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayNameOrDescriptionOrKeywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayNameOrDescriptionOrKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link LocalizedURIType }{@code >}
     * {@link JAXBElement }{@code <}{@link LocalizedNameType }{@code >}
     * {@link Element }
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link LocalizedURIType }{@code >}
     * {@link JAXBElement }{@code <}{@link LogoType }{@code >}
     * {@link JAXBElement }{@code <}{@link KeywordsType }{@code >}
     * {@link JAXBElement }{@code <}{@link LocalizedNameType }{@code >}
     * 
     * 
     */
    public List<Object> getDisplayNameOrDescriptionOrKeywords() {
        if (displayNameOrDescriptionOrKeywords == null) {
            displayNameOrDescriptionOrKeywords = new ArrayList<Object>();
        }
        return this.displayNameOrDescriptionOrKeywords;
    }

}
