//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.15 at 03:44:49 PM MSK 
//


package se.signatureservice.messages.saml2.metadata.ui.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for DiscoHintsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscoHintsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}IPHint"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}DomainHint"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:metadata:ui}GeolocationHint"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscoHintsType", propOrder = {
    "ipHintOrDomainHintOrGeolocationHint"
})
public class DiscoHintsType {

    @XmlElementRefs({
        @XmlElementRef(name = "GeolocationHint", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IPHint", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DomainHint", namespace = "urn:oasis:names:tc:SAML:metadata:ui", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> ipHintOrDomainHintOrGeolocationHint;

    /**
     * Gets the value of the ipHintOrDomainHintOrGeolocationHint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipHintOrDomainHintOrGeolocationHint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIPHintOrDomainHintOrGeolocationHint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Element }
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getIPHintOrDomainHintOrGeolocationHint() {
        if (ipHintOrDomainHintOrGeolocationHint == null) {
            ipHintOrDomainHintOrGeolocationHint = new ArrayList<Object>();
        }
        return this.ipHintOrDomainHintOrGeolocationHint;
    }

}
