//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 10:15:40 AM CEST 
//


package org.certificateservices.messages.csexport.data.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TokenTypeLifeCycleRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TokenTypeLifeCycleRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tokenEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tokenClasses">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tokenClass" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tokenAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="credentialSubTypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="credentialSubType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TokenTypeLifeCycleRule", propOrder = {
    "tokenEvent",
    "tokenClasses",
    "tokenAction",
    "credentialSubTypes",
    "enabled"
})
public class TokenTypeLifeCycleRule {

    @XmlElement(required = true)
    protected String tokenEvent;
    @XmlElement(required = true)
    protected TokenTypeLifeCycleRule.TokenClasses tokenClasses;
    @XmlElement(required = true)
    protected String tokenAction;
    @XmlElement(required = true)
    protected TokenTypeLifeCycleRule.CredentialSubTypes credentialSubTypes;
    protected boolean enabled;

    /**
     * Gets the value of the tokenEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenEvent() {
        return tokenEvent;
    }

    /**
     * Sets the value of the tokenEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenEvent(String value) {
        this.tokenEvent = value;
    }

    /**
     * Gets the value of the tokenClasses property.
     * 
     * @return
     *     possible object is
     *     {@link TokenTypeLifeCycleRule.TokenClasses }
     *     
     */
    public TokenTypeLifeCycleRule.TokenClasses getTokenClasses() {
        return tokenClasses;
    }

    /**
     * Sets the value of the tokenClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenTypeLifeCycleRule.TokenClasses }
     *     
     */
    public void setTokenClasses(TokenTypeLifeCycleRule.TokenClasses value) {
        this.tokenClasses = value;
    }

    /**
     * Gets the value of the tokenAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenAction() {
        return tokenAction;
    }

    /**
     * Sets the value of the tokenAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenAction(String value) {
        this.tokenAction = value;
    }

    /**
     * Gets the value of the credentialSubTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TokenTypeLifeCycleRule.CredentialSubTypes }
     *     
     */
    public TokenTypeLifeCycleRule.CredentialSubTypes getCredentialSubTypes() {
        return credentialSubTypes;
    }

    /**
     * Sets the value of the credentialSubTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenTypeLifeCycleRule.CredentialSubTypes }
     *     
     */
    public void setCredentialSubTypes(TokenTypeLifeCycleRule.CredentialSubTypes value) {
        this.credentialSubTypes = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="credentialSubType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "credentialSubType"
    })
    public static class CredentialSubTypes {

        @XmlElement(required = true)
        protected List<String> credentialSubType;

        /**
         * Gets the value of the credentialSubType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the credentialSubType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCredentialSubType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCredentialSubType() {
            if (credentialSubType == null) {
                credentialSubType = new ArrayList<String>();
            }
            return this.credentialSubType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tokenClass" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tokenClass"
    })
    public static class TokenClasses {

        @XmlElement(required = true)
        protected List<String> tokenClass;

        /**
         * Gets the value of the tokenClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tokenClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTokenClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTokenClass() {
            if (tokenClass == null) {
                tokenClass = new ArrayList<String>();
            }
            return this.tokenClass;
        }

    }

}
