//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.20 at 06:19:56 PM CEST 
//


package org.signatureservice.messages.authcontsaci1.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.authcontsaci1.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IdAttributes_QNAME = new QName("http://id.elegnamnden.se/auth-cont/1.0/saci", "IdAttributes");
    private final static QName _SAMLAuthContext_QNAME = new QName("http://id.elegnamnden.se/auth-cont/1.0/saci", "SAMLAuthContext");
    private final static QName _AttributeMapping_QNAME = new QName("http://id.elegnamnden.se/auth-cont/1.0/saci", "AttributeMapping");
    private final static QName _AuthContextInfo_QNAME = new QName("http://id.elegnamnden.se/auth-cont/1.0/saci", "AuthContextInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.authcontsaci1.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SAMLAuthContextType }
     * 
     */
    public SAMLAuthContextType createSAMLAuthContextType() {
        return new SAMLAuthContextType();
    }

    /**
     * Create an instance of {@link AuthContextInfoType }
     * 
     */
    public AuthContextInfoType createAuthContextInfoType() {
        return new AuthContextInfoType();
    }

    /**
     * Create an instance of {@link AttributeMappingType }
     * 
     */
    public AttributeMappingType createAttributeMappingType() {
        return new AttributeMappingType();
    }

    /**
     * Create an instance of {@link IdAttributesType }
     * 
     */
    public IdAttributesType createIdAttributesType() {
        return new IdAttributesType();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/auth-cont/1.0/saci", name = "IdAttributes")
    public JAXBElement<IdAttributesType> createIdAttributes(IdAttributesType value) {
        return new JAXBElement<IdAttributesType>(_IdAttributes_QNAME, IdAttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAMLAuthContextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/auth-cont/1.0/saci", name = "SAMLAuthContext")
    public JAXBElement<SAMLAuthContextType> createSAMLAuthContext(SAMLAuthContextType value) {
        return new JAXBElement<SAMLAuthContextType>(_SAMLAuthContext_QNAME, SAMLAuthContextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/auth-cont/1.0/saci", name = "AttributeMapping")
    public JAXBElement<AttributeMappingType> createAttributeMapping(AttributeMappingType value) {
        return new JAXBElement<AttributeMappingType>(_AttributeMapping_QNAME, AttributeMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthContextInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/auth-cont/1.0/saci", name = "AuthContextInfo")
    public JAXBElement<AuthContextInfoType> createAuthContextInfo(AuthContextInfoType value) {
        return new JAXBElement<AuthContextInfoType>(_AuthContextInfo_QNAME, AuthContextInfoType.class, null, value);
    }

}
