//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.26 at 09:40:10 AM CET 
//


package org.signatureservice.messages.sweeid2.dssextenstions1_1.jaxb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertRequestPropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertRequestPropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:2.0:assertion}AuthnContextClassRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}RequestedCertAttributes" minOccurs="0"/>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}OtherProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CertType" default="PKC">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="PKC"/>
 *             &lt;enumeration value="QC"/>
 *             &lt;enumeration value="QC/SSCD"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertRequestPropertiesType", propOrder = {
    "authnContextClassRef",
    "requestedCertAttributes",
    "otherProperties"
})
public class CertRequestPropertiesType {

    @XmlElement(name = "AuthnContextClassRef", namespace = "urn:oasis:names:tc:SAML:2.0:assertion")
    @XmlSchemaType(name = "anyURI")
    protected List<String> authnContextClassRef;
    @XmlElement(name = "RequestedCertAttributes")
    protected RequestedAttributesType requestedCertAttributes;
    @XmlElement(name = "OtherProperties")
    protected AnyType otherProperties;
    @XmlAttribute(name = "CertType")
    protected String certType;

    /**
     * The URI reference(s) to the requested level of assurance with which the
     *                         certificate subject should be authenticated.
     *                     Gets the value of the authnContextClassRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authnContextClassRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthnContextClassRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAuthnContextClassRef() {
        if (authnContextClassRef == null) {
            authnContextClassRef = new ArrayList<String>();
        }
        return this.authnContextClassRef;
    }

    /**
     * Gets the value of the requestedCertAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedAttributesType }
     *     
     */
    public RequestedAttributesType getRequestedCertAttributes() {
        return requestedCertAttributes;
    }

    /**
     * Sets the value of the requestedCertAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedAttributesType }
     *     
     */
    public void setRequestedCertAttributes(RequestedAttributesType value) {
        this.requestedCertAttributes = value;
    }

    /**
     * Gets the value of the otherProperties property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getOtherProperties() {
        return otherProperties;
    }

    /**
     * Sets the value of the otherProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setOtherProperties(AnyType value) {
        this.otherProperties = value;
    }

    /**
     * Gets the value of the certType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertType() {
        if (certType == null) {
            return "PKC";
        } else {
            return certType;
        }
    }

    /**
     * Sets the value of the certType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertType(String value) {
        this.certType = value;
    }

}
