//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.26 at 09:40:10 AM CET 
//


package org.signatureservice.messages.sweeid2.dssextenstions1_1.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SignResponseExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignResponseExtensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}ResponseTime"/>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}Request" minOccurs="0"/>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}SignerAssertionInfo" minOccurs="0"/>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}SignatureCertificateChain" minOccurs="0"/>
 *         &lt;element ref="{http://id.elegnamnden.se/csig/1.1/dss-ext/ns}OtherResponseInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignResponseExtensionType", propOrder = {
    "responseTime",
    "request",
    "signerAssertionInfo",
    "signatureCertificateChain",
    "otherResponseInfo"
})
public class SignResponseExtensionType {

    @XmlElement(name = "ResponseTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar responseTime;
    @XmlElement(name = "Request")
    protected byte[] request;
    @XmlElement(name = "SignerAssertionInfo")
    protected SignerAssertionInfoType signerAssertionInfo;
    @XmlElement(name = "SignatureCertificateChain")
    protected CertificateChainType signatureCertificateChain;
    @XmlElement(name = "OtherResponseInfo")
    protected AnyType otherResponseInfo;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the responseTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResponseTime() {
        return responseTime;
    }

    /**
     * Sets the value of the responseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResponseTime(XMLGregorianCalendar value) {
        this.responseTime = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRequest(byte[] value) {
        this.request = value;
    }

    /**
     * Gets the value of the signerAssertionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SignerAssertionInfoType }
     *     
     */
    public SignerAssertionInfoType getSignerAssertionInfo() {
        return signerAssertionInfo;
    }

    /**
     * Sets the value of the signerAssertionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignerAssertionInfoType }
     *     
     */
    public void setSignerAssertionInfo(SignerAssertionInfoType value) {
        this.signerAssertionInfo = value;
    }

    /**
     * Gets the value of the signatureCertificateChain property.
     * 
     * @return
     *     possible object is
     *     {@link CertificateChainType }
     *     
     */
    public CertificateChainType getSignatureCertificateChain() {
        return signatureCertificateChain;
    }

    /**
     * Sets the value of the signatureCertificateChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificateChainType }
     *     
     */
    public void setSignatureCertificateChain(CertificateChainType value) {
        this.signatureCertificateChain = value;
    }

    /**
     * Gets the value of the otherResponseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getOtherResponseInfo() {
        return otherResponseInfo;
    }

    /**
     * Sets the value of the otherResponseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setOtherResponseInfo(AnyType value) {
        this.otherResponseInfo = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
